---
clusterGroup:
  name: hub
  namespaces:
    vault:
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    external-secrets:
    ansible-automation-platform:
    openshift-cnv:
    openshift-storage:
    edge-gitops-vms:
    aap-config:
  subscriptions:
    aap-operator:
      name: ansible-automation-platform-operator
      namespace: ansible-automation-platform
      channel: stable-2.6
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1
    openshift-data-foundation:
      name: odf-operator
      namespace: openshift-storage
    openshift-virtualization:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      channel: stable
  applications:
    aap:
      name: ansible-automation-platform
      namespace: ansible-automation-platform
      chart: ansible-automation-platform-instance
      chartVersion: 0.1.*
    aap-config:
      name: aap-config
      namespace: aap-config
      chart: aap-config
      chartVersion: 0.1.*
      extraValueFiles:
        - $patternref/overrides/values-aap-config-aeg.yaml
    edge-gitops-vms:
      name: edge-gitops-vms
      namespace: edge-gitops-vms
      chart: edge-gitops-vms
      chartVersion: 0.3.*
      extraValueFiles:
        - $patternref/overrides/values-egv-vms.yaml
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      argoProject: hub
      chart: openshift-external-secrets
      chartVersion: 0.0.*
    odf:
      name: odf
      namespace: openshift-storage
      chart: openshift-data-foundations
      chartVersion: 0.2.*
      extraValueFiles:
        - $patternref/overrides/values-odf-chart.yaml
    ensure-openshift-console-plugins:
      name: ensure-openshift-console-plugins
      namespace: openshift-console
      chart: ensure-openshift-console-plugins
      chartVersion: 0.1.*
      extraValueFiles:
        - '$patternref/overrides/values-console-plugins.yaml'
    openshift-cnv:
      name: openshift-cnv
      namespace: openshift-cnv
      chart: openshift-virtualization-instance
      chartVersion: 0.1.*
    vault:
      name: vault
      namespace: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*
  imperative: {}
  managedClusterGroups: {}
